[package]
name = "ws2812-async"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smart-leds = "0.3.0"
embedded-hal-async = { version = "0.1.0-alpha.3" }
